# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  release:
    types: [created, released]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Clean
      run: go clean -v ./...

    - name: Format
      run: go fmt -v ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
