# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  release:
    types: [created, released]

jobs:
  build:
    runs-on: ubuntu-latest  # Base OS for all builds

    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]

    steps:
      - uses: actions/checkout@v3  # Check out your code

      - name: Set up Node.js v20 
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22' # Or your desired Go version

      - name: Build Binaries
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -tags netgo -a -v -o dist/${{ matrix.os }}-${{ matrix.goarch }}/napp .
